- type: entity
  parent: BaseAction
  id: ActionActivateAutoinjector
  name: "Активувати автоін'єктор"
  description: "Активуйте свій автоін'єктор, щоб ввести хімікати у кров."
  categories: [ HideSpawnMenu ]
  components:
  - type: Action
    checkCanInteract: false
    checkConsciousness: false
    itemIconStyle: NoItem
    icon:
      sprite: _Goobstation/Actions/modsuit.rsi
      state: stim
    useDelay: 70
  - type: InstantAction
    event: !type:ActionActivateAutoInjectorEvent {}

- type: entity
  parent: BaseAction
  id: ActionActivateSecondSkin
  name: "Активувати Другу Шкіру"
  description: "Покрийте своє тіло броньованою захисною рідиноподібною речовиною"
  categories: [ HideSpawnMenu ]
  components:
  - type: Action
    checkCanInteract: false
    itemIconStyle: NoItem
    useDelay: 2
    icon:
      sprite: _Goobstation/Clothing/OuterClothing/second_skin.rsi
      state: action
  - type: InstantAction
    event: !type:ActionActivateSecondSkin
