# SPDX-FileCopyrightText: 2025 CrateTheDragon <dragon.felcon@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Pirate Changelog

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write

jobs:
  pirate_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd Tools/changelog
          npm install
        shell: bash

      - name: Install js-yaml
        run: |
          npm install js-yaml
        shell: bash

      - name: Generate Pirate Changelog
        run: |
          node Tools/pirate_changelog/generate_pirate_changelog.js
        shell: bash

      - name: Commit Pirate Changelog
        run: |
          git config --global user.name "Pirate Changelog Bot"
          git config --global user.email "pirate-bot@users.noreply.github.com"
          git add Resources/Changelog/pirate.yml
          git commit -m "Update pirate.yml from PR #${{ github.event.number }}" || echo "No changes to commit"
          git push
        shell: bash